require: rubocop-rails

Layout/LineLength:
  Exclude:
    - Gemfile
    - Rakefile
    - db/**/*
    - config/**/*

Metrics/MethodLength:
  ExcludedMethods:
    - create
    - update

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# Pending Cops

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
