before_install: nvm install node
install:
  - bundle install --jobs=3 --retry=3
  - yarn --frozen-lockfile
cache:
  bundler: true
  yarn: true
  directories: /home/travis/.rvm/
script: bundle exec rake test test:system
