services: postgresql
before_install: nvm install node
install:
  - bundle install --jobs=3 --retry=3
  - yarn --frozen-lockfile
cache:
  bundler: true
  yarn: true
  directories: /home/travis/.rvm/
before_script: psql -c 'create database market_test;' -U postgres
script:
  - rake
  - rake test:system
